### ISSUE TITLE
Dark background when starting the app

### ISSUE THREAD

**Issue by ZeikoFr** [FreeTubeApp/FreeTube#1107]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
When starting the app there's a white flash before goin in the main menu of freetube

**Describe the solution you'd like to see implemented**
Remove the whit flash

**Screenshots**
Sometimes people have screenshots from mock-ups or other projects. Add them here.

**Additional context**
Manjaro KDE fully updated
Freetube appimage

![output](https://user-images.githubusercontent.com/54892453/110845931-780bf480-82ab-11eb-806a-05baefa5b5c6.gif)

**Comment by PrestonN** [comment]
I'm not sure I understand what you're talking about. I know that there was a white flash that would show up a _long_ time ago due to a delay in setting the theme, though that should have been fixed for a while. What Operating system are you on (Please don't delete the template, we really benefit from this information)? Could you provide a gif of this happening? I don't experience this on my machine so I cannot see what's going on.

**Comment by ZeikoFr** [comment]
> I'm not sure I understand what you're talking about. I know that there was a white flash that would show up a _long_ time ago due to a delay in setting the theme, though that should have been fixed for a while. What Operating system are you on (Please don't delete the template, we really benefit from this information)? Could you provide a gif of this happening? I don't experience this on my machine so I cannot see what's going on.

Hi, I've updated the post, sorry the start of the gif is a bit long but you can clearly see the white flashing

**Comment by Atrate** [comment]
Can confirm. The white flash is significantly shorter (less than 0.1s) when using a fast SSD or even loading the Freetube files into a ramdisk, but it still exists

**Comment by arrowgent** [comment]
white flash started happening for me also using v0.12.0
possibly related to:
Updated to Electron v12

previous versions did not do this.

the flash only occurs when launching Freetube.

**Comment by ckorder** [comment]
v0.11.2 Beta .deb version as well. but visibility rly depends on the loading time of the application.
for its less than 0.1 sec if my cpu isn't used heavily

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
+1 to solve this. 

https://user-images.githubusercontent.com/73130443/123301944-b603f000-d50b-11eb-9477-8f92f27664f1.mp4

**Comment by peepopoggers** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc
#1502

**Comment by peepopoggers** [comment]
Updated the above PR and it should be working unless others have problems with it.
