### ISSUE TITLE
Can't load certain videos

### ISSUE THREAD

**Issue by hcgrove** [FreeTubeApp/FreeTube#1438]
When I try to watch e.g.:
https://youtu.be/bvybMVRaND0
or
https://youtu.be/SlldJetZwcQ

I get the following three messages:
"Local API Error (Click to copy): Error: Status code: 404"
"Falling back to invidious API"
"Invidious API Error (Click to copy): {"error":"Could not extract video info. Instance is likely blocked."}"

(and no video)

I couldn't find another report of this problem, but if one exists, point me to it and close this.

This is on Debian 10, fully upgraded.
I just upgraded the freetube client to version 0.13.1 (over 0.11.3) from https://freetubeapp.io/#download (the x86 debian package) and succesfully reproduced this behaviour.

**Comment by hcgrove** [comment]
This might have been a temporary

**Comment by hcgrove** [comment]
It turns out that the problem was only gone on some videos, like the first one I mentioned above, now I got the same behavious on:
https://youtu.be/GkgPIJp8_30
but it's not reproducible, when I try again, I only get the first two of the mentioned messages nd then the video starts.

**Comment by 7echLife** [comment]
I'm having this issue now. I tried watching 2 videos and even 5 videos from history and they all failed to load.

**Comment by jantomicky** [comment]
I can't play any video right now, everything fails.

**Comment by axeII** [comment]
Same here I am unfortunately unable to play any video 😞 . Did API change?

**Comment by stpnwf** [comment]
same issue here

**Comment by ssnor** [comment]
I have the same issue.

**Comment by Yoss1960** [comment]
I too am seeing this behaviour.

In case my location matters;  I'm in South West England.

**Comment by Akruidenberg** [comment]
Same here.

**Comment by DrunkenBlyatHvH** [comment]
same here in germany

**Comment by johnno66** [comment]
Same here since this afternoon (Netherlands)

**Comment by Ralph2024cdnis** [comment]
Same here in Hong Kong

**Comment by DrunkenBlyatHvH** [comment]
im also on linux

**Comment by thescheff** [comment]
Change the invidius instance in the settings. **invidious.snopyta.org** is down.
![freetube](https://user-images.githubusercontent.com/13017161/122962844-15d08e80-d386-11eb-9ba6-951d5126802e.png)

This works for me.

**Comment by johnno66** [comment]
> Change the invidius instance in the settings. **invidious.snopyta.org** is down.

Thanks, Invidious playback now works, but the original error ("Local API Error (Click to copy): Error: Status code: 404") still remains

**Comment by spoergsmaal** [comment]
> 
> 
> Change the invidius instance in the settings. **invidious.snopyta.org** is down.
> 
> This works for me.

also works for me!

**Comment by ChunkyProgrammer** [comment]
Pretty sure it has to do with this: https://github.com/fent/node-ytdl-core/issues/939

**Comment by EvilGremlin** [comment]
+1
Unable to play almost any video for last hours. Youtube definitely changed something.

**Comment by rjdg14** [comment]
I've discovered that every video is now resulting in the 404 error. Age restricted videos began having this issue (after ytdl's fix a few weeks ago) several days back.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Response from dev

![Screenshot_20210623-100307.png](https://user-images.githubusercontent.com/73130443/123059728-954b7580-d3f9-11eb-85a8-46e63af86e9c.png)

**Comment by RastiGiG** [comment]
Could you guys pls link the the issue here as well? Can't click a link in a picture sadly ;)

**Comment by fantawttw** [comment]
> Could you guys pls link the the issue here as well? Can't click a link in a picture sadly ;)

I think this is the issue mentioned
[https://github.com/fent/node-ytdl-core/issues/939]

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Could you guys pls link the the issue here as well? Can't click a link in a picture sadly ;)

https://github.com/fent/node-ytdl-core/issues/939

https://github.com/fent/node-ytdl-core/pull/938

**Comment by MattRGX** [comment]
I'm not able to see any video from my subscription list right now. I tried to change the invidious instance but nothing change !

Here are my settings ! 

[image](https://user-images.githubusercontent.com/58740578/123113708-0bbe9680-d43f-11eb-80e9-54513a04c46c.png)

**Comment by Ralph2024cdnis** [comment]
> I'm not able to see any video from my subscription list right now. I tried to change the invidious instance but nothing change !
> 
> Here are my settings !
> 
> [image](https://user-images.githubusercontent.com/58740578/123113708-0bbe9680-d43f-11eb-80e9-54513a04c46c.png)

yewtu.be doesn't work too, I tried

**Comment by MattRGX** [comment]
> 
> 
> > I'm not able to see any video from my subscription list right now. I tried to change the invidious instance but nothing change !
> > Here are my settings !
> > [image](https://user-images.githubusercontent.com/58740578/123113708-0bbe9680-d43f-11eb-80e9-54513a04c46c.png)
> 
> yewtu.be doesn't work too, I tried.
> 
> I am using invidious.kavin.rocks

yewtu.be is working on my side !

**Comment by jilv220** [comment]
https://invidious.kavin.rocks 
working for me.

**Comment by rebelga** [comment]
No video working for me either.  v0.13.1 Beta

**Comment by KarkanAlzwayed** [comment]
> Change the invidius instance in the settings. **invidious.snopyta.org** is down.
> ![freetube](https://user-images.githubusercontent.com/13017161/122962844-15d08e80-d386-11eb-9ba6-951d5126802e.png)
> 
> This works for me.

Thank you for this, it's fixed it for me. Any idea why the option to change the resolution is gone now? do I need to open a new issue for it, or is it being addressed?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> > Thank you for this, it's fixed it for me. Any idea why the option to change the resolution is gone now? do I need to open a new issue for it, or is it being addressed?

The resolution problem ur facing is a WIP. U dont need to open an issue for this.

**Comment by KarkanAlzwayed** [comment]
Excuse my ignorance, what is WIP?  @efb4f5ff-1298-471a-8973-3d47447115dc

**Comment by realfraze** [comment]
> 
> 
> Excuse my ignorance, what is WIP? @efb4f5ff-1298-471a-8973-3d47447115dc

unless i'm very mistaken, he just means "work in progress"

**Comment by KarkanAlzwayed** [comment]
@realfraze makes sense. It was there last week. I was able to change the video resolution while the video is playing, but now I can't. The option is completely gone

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> @realfraze makes sense. It was there last week. I was able to change the video resolution while the video is playing, but now I can't. The option is completely gone

What u can do tho is post ur comment about resolution here https://github.com/FreeTubeApp/FreeTube/issues/595 for visibility.

**Comment by trych** [comment]
I can't load any video either. Doesn't even seem to matter what I put in Invidious Instance.

**Comment by MattRGX** [comment]
> 
> 
> I can't load any video either. Doesn't even seem to matter what I put in Invidious Instance.

the same for me ! Whatever instance i put, loads of video doesn't work

**Comment by precession25920** [comment]
> 
> 
> Change the invidius instance in the settings. **invidious.snopyta.org** is down.
> ![freetube](https://user-images.githubusercontent.com/13017161/122962844-15d08e80-d386-11eb-9ba6-951d5126802e.png)
> 
> This works for me.



> 
> 
> > Change the invidius instance in the settings. **invidious.snopyta.org** is down.
> > ![freetube](https://user-images.githubusercontent.com/13017161/122962844-15d08e80-d386-11eb-9ba6-951d5126802e.png)
> > This works for me.
> 
> Thank you for this, it's fixed it for me. Any idea why the option to change the resolution is gone now? do I need to open a new issue for it, or is it being addressed?

Works for me

**Comment by precession25920** [comment]
> > Change the invidius instance in the settings. **invidious.snopyta.org** is down.
Works for me too.

**Comment by precession25920** [comment]
> Change the invidius instance in the settings. **invidious.snopyta.org** is down.

Works for me too.

**Comment by unsungNovelty** [comment]
> I can't load any video either. Doesn't even seem to matter what I put in Invidious Instance.

> > I can't load any video either. Doesn't even seem to matter what I put in Invidious Instance.
> 
> the same for me ! Whatever instance i put, loads of video doesn't work

@MattRGX @trych - After you change the invidious instance, you need to refresh the video from subscription page to reload the whole thing. If you haven't, you should.

![image](https://user-images.githubusercontent.com/11845908/123461769-1af04080-d607-11eb-91f6-9b8b57f3ca45.png)

**Comment by trych** [comment]
> After you change the invidious instance, you need to refresh the video from subscription page to reload the whole thing. If you haven't, you should.

Nope. Doesn't change a thing unfortunately. Restarting the app doesn't help either. I cannot play a single video, no matter what.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> > Could you guys pls link the the issue here as well? Can't click a link in a picture sadly ;)
> 
> https://github.com/fent/node-ytdl-core/issues/939
> 
> https://github.com/fent/node-ytdl-core/pull/938

Quick update the upstream issue has been resolved and merged. Now its just a matter of time for Freetube to work again.

**Comment by trych** [comment]
Seems to work again for most videos!
But I still seem to be able to play age restricted videos (which usually is FreeTube's most useful feature for me).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> But I still seem to be able to play age restricted videos (which usually is FreeTube's most useful feature for me).

IIRC age restricted videos were already broken before this issue occurred. Its a known problem and is been worked on.

**Comment by trych** [comment]
Ah, ok. Thanks for the info!

**Comment by robguthm** [comment]
> > I can't load any video either. Doesn't even seem to matter what I put in Invidious Instance.
> 
> > > I can't load any video either. Doesn't even seem to matter what I put in Invidious Instance.
> > 
> > 
> > the same for me ! Whatever instance i put, loads of video doesn't work
> 
> @MattRGX @trych - After you change the invidious instance, you need to refresh the video from subscription page to reload the whole thing. If you haven't, you should.
> 
> ![image](https://user-images.githubusercontent.com/11845908/123461769-1af04080-d607-11eb-91f6-9b8b57f3ca45.png)

refreshing worked for me. still getting error text but video will play after fallback using https:/yt.cyberhost.uk

Thanks

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hotfix update is available to download:

https://github.com/FreeTubeApp/FreeTube/releases/tag/v0.13.2-beta

https://freetubeapp.io/#download

This should resolve this issue.

**Comment by arrowgent** [comment]
https://api.invidious.io/

go here and verify a current node is working
set it to your freetube invidious
done deal.

ON THIS NOTE
it would be good if freetube could query this api and tell the user if certain Invidious instances are good/down/etc

SECONDLY
would it be possible to allow updating (locally) the freetube Local invidious instance?
without needing to wait for a freetube patch update?

**Comment by Kreyren** [comment]
> Proposing to use random instance on each try with configurable retry attempts

> Option to blacklist instances that are getting blocked too often e.g. snopyta.org should also be integrated so that the load can be distributed evenly

-- https://github.com/FreeTubeApp/FreeTube/issues/1472

**Comment by Kreyren** [comment]
> IIRC age restricted videos were already broken before this issue occurred. Its a known problem and is been worked on. @efb4f5ff-1298-471a-8973-3d47447115dc

See https://github.com/FreeTubeApp/FreeTube/issues/1296

**Comment by arrowgent** [comment]
> > Proposing to use random instance on each try with configurable retry attempts
> 
> > Option to blacklist instances that are getting blocked too often e.g. snopyta.org should also be integrated so that the load can be distributed evenly
> 
> -- #1472


creating a blocklist and/or using a random selection list _creates a new hash of problems and errors_

instead of attempting to automate this process; better Error messaging can be displayed
instead of a large block of text with a 404 at the end, give a minor popup requesting to use an alternative Invidious api instance

a block selection if automated
Servers: -> Selected
server 1 -> no
server 2 -> yes (selected)
server 3 -> yes (selected)
server 4 -> no
clicking left/right arrow to move server to NotSelected : Selected boxes.


**i specifically choose US based instances due to Latency/ping**

**Comment by Kreyren** [comment]
Latency up to to 1000ms is irelevant while playing videos as they get preloaded in a buffer and doesn't require any real time input.

Agree with better messaging, but disagree with automatization as the more auomated this is the better since all videos on invidious now require me to use redirect.invidious.io and go through instances which is pita.

Also in the world where all instances works pressing the button is still annoying

**Comment by GilgusMaximus** [comment]
I am going to close this, as the original problem was solved with the hotfix and better error displays are on our list anyways and discussed in many other issues as well

**Comment by zh54tg234f** [comment]
@GilgusMaximus  please think about reopening since the issue is back and there is no serious fallback to utilize invidious. (which is better maintained and quicker updated, no offense) 

https://github.com/FreeTubeApp/FreeTube/issues/1296
