### ISSUE TITLE
Every page is blank white

### ISSUE THREAD

**Issue by burny0202** [FreeTubeApp/FreeTube#1689]
**Behavior of the program**
The whole app is just a blank white page whatever I click.
Tried removing old config, also tried all the builds from AUR

**Expected behavior**
Different Menus...Search etc working

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Open FreeTube
2. Click anything or search anything
3. Title of window changes.....Nothing else happens

**Link to video**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/37351981/132992801-dd1cd25e-c45b-47ee-a3cb-2c3f68fc1762.png)

**Environment Information (please complete the following information):**
 - OS: Arch
 - OS Version: Rolling
 - FreeTube version: 0.14.0(-beta) - AUR Versions 14.0.1 & 14.0.2
 - Installation Method (If applicable): AUR - YAY
 - Primary API Used: Can't change settings 

**Additional context**
N/A

**Comment by toby63** [comment]
These versions do not exist.

And please use the issue template instead of ignoring it.

**Comment by burny0202** [comment]
Weird...No template appeared yesterday. 
I've updated it today, thanks for your help

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
this also just happened to me

https://user-images.githubusercontent.com/73130443/133053002-16a7936e-d033-4426-8b24-59684fccdaa6.mp4

v0.14.0-nightly-1164 Beta

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
this has been fix in https://github.com/FreeTubeApp/FreeTube/pull/1723

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This happened to me again build 1224

**Comment by PikachuEXE** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 
If you can reproduce I think you can find out what error is raised in dev tool

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@PikachuEXE 

![signal-2021-09-24-105146.png](https://user-images.githubusercontent.com/73130443/134646920-34b8d29f-1020-4a3e-9486-58a066a9ef11.png)

**Comment by PikachuEXE** [comment]
That's due to invidious instances cannot be fetched...
I have no idea how this should be fixed 😅

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
That's weird? I dont have invidious api enabled how is that even related to not being connected to the internet

**Comment by PikachuEXE** [comment]
I think FT is trying to get invidious instances on start up anyway

**Comment by peepopoggers** [comment]
@PikachuEXE it is one of the first functions executed

**Comment by daraspul** [comment]
sorry im still confused has this issue been solved?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
No yet, there is a fix out https://github.com/FreeTubeApp/FreeTube/pull/1755. We still need to do some tests before it will be merged.

**Comment by peepopoggers** [comment]
Turn off your internet and launch FreeTube and it will show this.
It would be much nicer to have a page saying - "no internet :(" than just a blank page.
It also does not load the themes which need to be addressed as they do not require internet.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
U should also navigate freely to the settings page

**Comment by peepopoggers** [comment]
not sure playlist and history would be able to work, reasoning: video information would not load

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
But it doesnt need to retrieve anything from the internet right? So you can just pull it from the local database

**Comment by peepopoggers** [comment]
Are titles and thumbnails stored locally??

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Im not about the thumbnails but the titles are otherwise couldn't export them right?

**Comment by peepopoggers** [comment]
ok well we should figure out the white blank theme issue before we get to that, then we can see how the program responds.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Could u guys test out the latest RC release this should fix this https://github.com/FreeTubeApp/FreeTube/discussions/1773

**Comment by burny0202** [comment]
Unfortunately it is still the same, although in dark mode.

i tried the .pacman in builds #1239  and #1249

Is there some kind of debug mode I can open it up in to see any errors? (Sorry I'm not the best with this kind of thing)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Yes, CTRL + SHIFT + I

switch to console and make a print screen of the errors in red

**Comment by burny0202** [comment]
![image](https://user-images.githubusercontent.com/37351981/135912538-65bbfd67-4e97-409c-8a1f-44f0ec0dd1b4.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@ChunkyProgrammer haven't had the time to look at ur PR yet but does it solve these errors?

**Comment by ChunkyProgrammer** [comment]
> @ChunkyProgrammer haven't had the time to look at ur PR yet but does it solve these errors?

It should fix the error

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Try out the latest nightly build

**Comment by burny0202** [comment]
Not sure if @ChunkyProgrammer 's fix is incorporated in the latest release, but still no joy, I'm afraid

**Comment by burny0202** [comment]
Tested this on the latest git, and it is now working.

Seems a little unresponsive and I get an error

![image](https://user-images.githubusercontent.com/37351981/143311482-8f1aa37c-cf51-4396-b2f4-65b674af6f31.png)

But it works

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Did the our latest release fix this for u?
