### ISSUE TITLE
[Bug]: Switching between 2 video pages displays incorrect videos in up next section and video description

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#2261]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Switch fast between 2 videos

https://user-images.githubusercontent.com/73130443/169858493-cd6a6176-44b1-4746-951b-0d418bca2b85.mp4

### Expected Behavior

Shows correct videos in Up Next section
Shows correct description under the video

### Issue Labels

inconsistent behavior, race condition, visual bug

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/e17bdf2aef89b17bffb008e99fcf78dd7b0d5c85

### Operating System Version

Win10 21H2

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by sarans-h** [comment]
Hiii @efb4f5ff-1298-471a-8973-3d47447115dc assign it to me if still open.

**Comment by sarans-h** [comment]
Hi @efb4f5ff-1298-471a-8973-3d47447115dc  I started the dev server by cloning the repo and running yarn just like it was mentioned in doc but found 

![Image](https://github.com/user-attachments/assets/e87ced41-21ae-4440-924a-ade8c186daab)

Am I missing something?

below is the complete error 

[e.txt](https://github.com/user-attachments/files/20725191/e.txt)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Looking at the recent commits and its probably due to the weblate commits failing. Will update soon on what you should do

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@sarans-h errors should be fixed after https://github.com/FreeTubeApp/FreeTube/pull/7560

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@sarans-h fixed now

**Comment by sarans-h** [comment]
hi i think @efb4f5ff-1298-471a-8973-3d47447115dc  the issue is fixed as the videos get finished the next video playing is same as shown in upnext with its own description.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
The issue is not fixed you just have to go forward and backward fast

**Comment by sarans-h** [comment]
I am sure u are saying forward and backward by arrow key i am finding difficult to replicate it. If u can explain more will be very thankful. (I tried moving back and forward fast using arrow keys of keyboard it is not changing the video)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Sorry but there is nothing else to it.

https://github.com/user-attachments/assets/840a36a8-0d2e-4696-98f5-e2e406076f61

**Comment by sarans-h** [comment]
which button u are using to change videos?????? @efb4f5ff-1298-471a-8973-3d47447115dc 
or just changing videos by clicking from upnext list?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ctrl + arrowkeyleft/right

**Comment by sarans-h** [comment]
this was only missing Thank you!

**Comment by sarans-h** [comment]
Sorry for troubling you @efb4f5ff-1298-471a-8973-3d47447115dc the shortcut key is not working for me using windows 10 . I think I can not help if you have any other suggestion i can try it 
Thank U(I checked my key combination is working using diff tools)
~ sarans-h

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hmm that's unfortunate. Its the only way to reproduce this so. Thank you for your efforts though. Hopefully you can find another issue you like to work on
