### ISSUE TITLE
[Bug]: where did my saved videos go?

### ISSUE THREAD

**Issue by ayvind** [FreeTubeApp/FreeTube#4969]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

click save. and now I can't find the saved for later playlist

### Expected Behavior

find the saved for later videos under playlist

### Issue Labels

accessibility issue

### FreeTube Version

v0.20.0 

### Operating System Version

linux

### Installation Method

AUR (Unofficial)

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.19.0 

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please make a screenrecording and show the following in this order

1. Show Playlist page
2. Search a video and bookmark it
3. Show Playlist page again

**Comment by ayvind** [comment]
do you realize that there is no way (to my knowledge) to show the most recently added video?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
You can sort in the playlist tab by Recently updated. Please follow the instructions above.

**Comment by ayvind** [comment]
I'm telling you, this does not work

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
You need to provide more information for us to help you.

**Comment by ayvind** [comment]
the 'sort by' only shows up on playlist overview. When I enter the playlist called 'Favorites' the latest added video does not show up. Neither is there any 'sort by' showing up. Just bookmarked videos of old..

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
it could be added to another playlist without you knowing you did it.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
You could have set your quick bookmark playlist as another one. Check if this is enabled in your playlist.

https://github.com/FreeTubeApp/FreeTube/assets/73130443/d9159b51-8fef-4690-906c-93540ae4d001

**Comment by ayvind** [comment]
no. the playlist don't appear with the most recent added vidoes

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@ayvind see https://github.com/FreeTubeApp/FreeTube/issues/4969#issuecomment-2061967605

**Comment by ayvind** [comment]
![image](https://github.com/FreeTubeApp/FreeTube/assets/51096396/e9bc2262-1a49-4a5a-939d-4f1079d84fb7)
how do you show the most recent added video here? It's doesn't happen when the page is big

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> You can sort in the playlist tab by Recently updated

I said Playlist tab and not within sorting within a playlist.

**Comment by ayvind** [comment]
4,517 videos - Last Updated On Apr 17, 2024

I have, but to no avail.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Final request for showing a screen recording.

Follow these new instructions:

1. Go into you Favorites playlist
2. Click on the quick bookmark button shown in the video above to enable quick bookmark for that playlist
3. Bookmark a video
4. Go back to the playlist to check if video has been added

**Comment by ayvind** [comment]
yes, it has been added:

4,517 videos - Last Updated On Apr 17, 2024.

but it does NOT show the most recently added video from that list of 4517 videos bookmarked

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
ok so your issue is solved right? You know where your saved video is.

**Comment by ayvind** [comment]
issue is NOT resolved, because the videos don't appear as most recent

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> find the saved for later videos under playlist

It is resolved. Video wont appear at the top of the playlist because sorting within a playlist hasnt been implemented in this version yet.
