### ISSUE TITLE
[Bug]: DASH using low quality audio

### ISSUE THREAD

**Issue by maep--** [FreeTubeApp/FreeTube#5678]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When using DASH, FreeTube appears to use a low bitrate audio format. There are very noticeable artifacts.

A good example to illustrate this is at the beginning of Fatboy Slim's Kalifornia in the Vocoder part. 
https://www.youtube.com/watch?v=uuzVVxx8pZY

In the official Youtube player the sound is very clear, while in FreeTube DASH player there are extremly bad artifacts. 

### Expected Behavior

The official Youtube player uses stream ID 251 for audio. FreeTube should do the same, or use 140, which is also a high bitrate stream. I would expect this behavior in particular for high definition video. With `yt-dlp -F` it's possible to get a list of stream IDs. 

### Issue Labels

usability issue

### FreeTube Version

v0.21.3 Beta
v0.22.1 Beta

### Operating System Version

Ubuntu

### Installation Method

.deb

### Primary API used

Local API

**Comment by maep--** [comment]
fixed in 0.22

**Comment by jspast** [comment]
Sorry to reactivate this issue, but I am still facing this same problem for _most_ videos, with the low quality opus 249 stream being used. It seems the player uses the 249 stream for every video that has it available, instead of 251. Are you sure it got fixed @maep-- ?

**Comment by maep--** [comment]
@jspast 

Thanks for pointing this out, I ws mistaken. This is still an issue.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing im favor of https://github.com/FreeTubeApp/FreeTube/issues/6138
