### ISSUE TITLE
[Bug]: Playback stops spontaneously after a few minutes

### ISSUE THREAD

**Issue by philpagel** [FreeTubeApp/FreeTube#6063]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. start any video
2. let it play
3. Playback stops at random after a few minutes. 

Playback can be resumed without problem but may stop again, later. 

I have the impression that it occurs more frequently when I switch to a different browser tab and let the video play in the background but have not hard evidence for that.

Edit/update: The bug does not occur as long as I stay "active" i.e. stay in the freetube window and e.g. move the mouse. It does happen after a while if I leave the computer alone – i.e. don't touch keyboard or mouse and just watch, or switch to a different desktop and keep working there.

### Expected Behavior

Video keeps playing until stopped manually or finished.

### Issue Labels

feature stopped working, inconsistent behavior

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Debian 12.7
X11, i3

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.20

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by b2ag** [comment]
Very annoying bug. Playback stops randomly. Playback position is not saved, so reopening the video (where is reload btw?) does not jump to the position it stopped but plays from start of the video. Can't correlate it with activity over here. Also tested a live stream which worked for as long as I could stand testing it (like 1 minute or 2).

**Comment by b2ag** [comment]
Nightly AppImage works for me. I tried `freetube_0.22.0-nightly-5063_amd64.AppImage`.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@philpagel please try the nightly build to check if its fixed for you. If you require more info see https://docs.freetubeapp.io/development/nightly-builds#downloading-nightly-builds

**Comment by b2ag** [comment]
I spoke too soon. Bug still in present in nightly 5063.

**Comment by philpagel** [comment]
I tried v0.22.0-nightly-5069 Beta and I still have the problem. It took quite some time, but eventually playback stopped when I spent time working on a different virtual desktop.

**Comment by b2ag** [comment]
I tried to git bisect between master v0.21.3-beta and v0.22.0-beta giving every commit 30 to 50 minutes testing. Sadly I failed to find something conclusive and ended up thinking this thing is unrelated to the new release. Also tried to find commits in development branch which I may have missed bisecting in master. But no look either, all good.

I only had a bad test result once when testing when I jumped to the very last commit: v0.22.0-beta. I was only 4 commits away and wanted to check if the thing went away on its own. It almost instantly stopped after 5 to 10 minutes. After trying 2 commits and 1 commit away, which tested good, I couldn't reproduce the bug anymore. Even with v0.22.0-beta. That one bad test was the last time I saw the sudden stop.

I don't know if it's the same for philpagel or fairking but I struggle to find a reproducer. Currently the stopping just looks very random (and currently also very rare) to me. So maybe something on the Serverside/Google/Invidious?

Needs a solid reproducer to investigate further if you ask me.

**Comment by b2ag** [comment]
@philpagel 
Is my experience even same as yours? Was the playback position reset for you too? So you had to do so back and fwd dance and manually find the position it stopped at? From your statement video could just have been paused for you. Just trying not hijack your issue with the random stops I've seen.

**Comment by philpagel** [comment]
> @philpagel Is my experience even same as yours? Was the playback position reset for you too? So did you have to do "reload dance" and manually find the position it stopped at to resume playback? From your statement video could just have been paused for you. Just trying not hijack your issue with the random stops I've seen.

I had mixed result: most of the time, the video did not reset and I could just restart it at the stop position. In more rare cases, the video was reset and I had to find the last position manually. Also the frequency of the bug occurring varies wildly: Sometimes it happens after just a few seconds, at other times it will play an entire video w/o problems or take like 20 minutes before it happens. 

I'll keep testing and report back if I see anything interesting or a change in behaviour.

**Comment by b2ag** [comment]
I just tried sky news live stream 30 minutes wired without VPN. Than 90 minutes wired with VPN exiting in Ireland. No luck so far in reproducing my issue.

I always had a stopped/reset video and needed to reload which seemed new to me. Frequency was also annoyingly high.

Maybe we should gather some data on frequency. Currently I saw the issue last a few days ago.

The peak annoyance of issue was like maybe around 10 stops that day.

I never had a "soft stop" where I could just press play to resume. Not being able to press reload and finding the position it stopped on made me post here. It seemed new and there was this recent new release of FreeTube. I also saw no problems with live streams because I didn't watch live streams. And testing that resulted in not triggering the thing so far. Couldn't figure out how to simulate bad connection and testing with a wired desktop pc.

**Comment by philpagel** [comment]
I almost thought, the problem went away on its own. but just a minute ago, I had another spontaneous stop. It definitely got a lot more rare. Initially I experienced it within minutes reliably while now it seems to occur more like once in a few hours. It's 99% "soft stops" for me. 

Given the fact that I am still running v0.22.0-nightly-5069 and the behavior changed over time, may suggest that it's an API problem...

**Comment by b2ag** [comment]
I'm back to thinking something is wrong in v0.22.0-beta. I saw the bug again in a video after 10 minutes and in another video 7, 37 and 43 minutes in. I than started a v0.21.3-beta instance next to a v0.22.0-beta instance, played the last video in parallel and only the v0.22 instance stopped three times (after 15, 34 and 43 minutes). Video was https://youtu.be/9a-n8ObM7wk .

**Comment by philpagel** [comment]
>  now it seems to occur more like once in a few hours.

Shouldn't have said that. I'm back to a stop every few minutes...

**Comment by absidue** [comment]
@philpagel Could you please confirm that it happens when the app is in the foreground? If it only stops while in the background it is a known issue that playback stops on Linux when switching to a different desktop or when the window is in the background sometimes.

As it doesn't happen on Windows and macOS I suspect that something in the window manager or desktop is backgrounding the process to boost power for foreground apps which is killing the playback.

**Comment by philpagel** [comment]
Yes, it does also happen when I am not leaving the desktop freetube is running on or doing anything at all other than watching.

**Comment by jeypawlik** [comment]
Having the same problem, video stops while it's open in the foreground on one of my monitors. It's not saving my spot in the video either.
Using v0.22.0 beta
When I open Freetube up again it sometimes works or sometimes gives the errors:
```
Local API Error: [UNPLAYABLE] Please sign in
Legacy Formats are not available for this video
```

It seems random when the errors do show up, errors still show up if I'm using an Invidious Instance. I haven't been able to replicate anything specific, but it sure is frustrating.

**Comment by b2ag** [comment]
I tried bisecting again. This time I started in the development branch, made sure to clean old build artifacts and tried to testing longer before marking as "good". Due to the random nature it is hard to define a commit as good.

I'll need some more time, but so far I can say it looks like the issue is already present in 406512f1f7a35c86645b914e13fade7b29849714 (v0.22.0-beta^2~316). My "maybe good" currently points at  62181016f83ac5410ea99638c5f81e0cc98f74ab (v0.22.0-beta^2~343) tested for about 4-5 hours.

**Comment by azurusnova** [comment]
I can also say that I have been encountering these random video stops as well. 

I would be watching a video and sometimes it will stop the playback and I would have to use CTRL+R to reset everything, and the playback where it left off would not be saved. This is with using the window either in theater or full screen and would just happen randomly. It happened again to me just now as it was what got me looking through here to see if anyone else has been encountering the same issue. I am glad I am not the only one. 

I will be keeping an eye open for any developments and will report any new findings if they show up as this issue seems to be quite random at best.

**Comment by b2ag** [comment]
Looks like b3ff837468845ab55eca5499e60c352ff2df506d (`v0.22.0-beta^2~318`) has introduced the problem. At least git bisect points at this commit over here.

**Comment by b2ag** [comment]
I did try the devtools to debug this some time ago, but the console itself showed no error. I remember the network tab showing some fails but they didn't seem "not normal" to me as the player recovered without interruption and I think I also saw the bug without any failed fetches in the network tab.

**Comment by b2ag** [comment]
Just checked it again. DevTools output is uneventful and the stop I saw didn't show any fails in the network tab. I had the "Stats" display on, but I see no hints there either. Bandwith, Buffered, Dropped Frames and Total Frames jumped to showing "NaN". Video ID, Media Formats (dash), Bitrate, Volume, Player Dimensions and Resolution stayed the same as when the video was playing. Player Dimension wasn't updated after exiting fullscreen.

**Comment by b2ag** [comment]
b3ff837468845ab55eca5499e60c352ff2df506d says live streams showed a similar behavior when using DASH. Problem "after 1 minute". Could fit or not. Who knows.

    * Use the HLS manifests for live streams

    The live DASH manifests are currently unusable on both API backends as
    they return 403s after 1 minute of playback. Unfortunately this means we
    lose the ability to seek and use the audio formats for live streams.

@absidue  Let me know when you have some debugging idea I can implement over here.

I also just noticed, that @jeypawlik's error looks like a 403.
> ```
> Local API Error: [UNPLAYABLE] Please sign in
> Legacy Formats are not available for this video
> ```

**Comment by absidue** [comment]
> b3ff837468845ab55eca5499e60c352ff2df506d says live streams showed a similar behavior when using DASH. Problem "after 1 minute". Could fit or not. Who knows.

@b2ag That commit is likely unrelated, considering you literally mentioned getting it on the lastest nightly and you guys were saying that it was happening for all videos whereas that was only for live streams, also you said everything looked fine in the logs and Network tab which would have lit up red for an HTTP 403 status code and FreeTube would have told you about it in the UI too. You would also not just be able to press play to keep going after the fact.

> I just noticed, that @jeypawlik's error looks like a 403.
> 
> > ```
> 
> > Local API Error: [UNPLAYABLE] Please sign in
> 
> > Legacy Formats are not available for this video
> 
> > ```

Nope, the 403s happen during playback and come from `*.googlevideo.com`, whereas that is failing well before that while fetching the information about the video and is likely caused by an IP block (see other issues for that, changing to a different VPN server will fix that).

**Comment by jeypawlik** [comment]
> > [b3ff837](https://github.com/FreeTubeApp/FreeTube/commit/b3ff837468845ab55eca5499e60c352ff2df506d) says live streams showed a similar behavior when using DASH. Problem "after 1 minute". Could fit or not. Who knows.
> 
> @b2ag That commit is likely unrelated, considering you literally mentioned getting it on the lastest nightly and you guys were saying that it was happening for all videos whereas that was only for live streams, also you said everything looked fine in the logs and Network tab which would have lit up red for an HTTP 403 status code and FreeTube would have told you about it in the UI too. You would also not just be able to press play to keep going after the fact.
> 
> > I just noticed, that @jeypawlik's error looks like a 403.
> > > 
> > 
> > 
> > > Local API Error: [UNPLAYABLE] Please sign in
> > 
> > 
> > > Legacy Formats are not available for this video
> > 
> > 
> > >
> 
> Nope, the 403s happen during playback and come from `*.googlevideo.com`, whereas that is failing well before that while fetching the information about the video and is likely caused by an IP block (see other issues for that, changing to a different VPN server will fix that).

I am using a VPN, however I'll change to a different server and the issue still persists. I'll change again and the video will just continue to pause or not play at all.

**Comment by b2ag** [comment]
I'm pretty sure it's commit b3ff837468845ab55eca5499e60c352ff2df506d. Unfortunately it's a mix of many commits/changes.  Maybe the change from video.js to shaka-player is to blame. The bug still happens for me (more frequent on sundays/holidays?), it's still annoying af and I don't know what to try next to help with debugging. If nothing changes I'll stick to 21.3 for the foreseeable future I guess.

@absidue Let me know if you want me to try something. Would be happy to add some debug modifications to the code to get some more data on the issue. Just let me know what to add and where to put it.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Could you test the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds) and see if the issue is resolved for you

**Comment by philpagel** [comment]
v0.22.1-nightly-5376 Beta still randomly stopping. :-(

**Comment by absidue** [comment]
@philpagel As you mentioned that it only happens if you unfocus the window or stay focused but stop interacting with it, it almost sounds like some kind of power saving setting on your device or weirdness with the tiling WM that you are using.

The fact that you can just hit play and it will just keep playing means that there were no errors or anything and it really just got paused by something. As there is no code in FreeTube to pause when you are idle, FreeTube actually explicitly tells your computer to stay active while the video is playing, I really think it is caused by something external to FreeTube. All I can suggest is that you try experimenting with different setups (distros, a non-tiling window manager, etc) and see if anything helps as there is nothing we can do about it on our side.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
this sounds like a duplicate https://github.com/FreeTubeApp/FreeTube/issues/4899

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
try https://github.com/FreeTubeApp/FreeTube/issues/4899#issuecomment-2151382157

**Comment by philpagel** [comment]
> @philpagel As you mentioned that it only happens if you unfocus the window or stay focused but stop interacting with it, it almost sounds like some kind of power saving setting on your device or weirdness with the tiling WM that you are using.

N o– it doe not only happen when the window goes out of focus. It also does while watching with that window active.

> The fact that you can just hit play and it will just keep playing means that there were no errors or anything and it really just got paused by something. As there is no code in FreeTube to pause when you are idle, FreeTube actually explicitly tells your computer to stay active while the video is playing, I really think it is caused by something external to FreeTube. All I can suggest is that you try experimenting with different setups (distros, a non-tiling window manager, etc) and see if anything helps as there is nothing we can do about it on our side.

I'll keep playing with it. But I still think its related to Freetube itself as it started happening immediately after a FreeTube update.

**Comment by philpagel** [comment]
> this sounds like a duplicate #4899

No – that one explicitly says it only happens when window is in background.

**Comment by philpagel** [comment]
> try [#4899 (comment)](https://github.com/FreeTubeApp/FreeTube/issues/4899#issuecomment-2151382157)

Thanks for the link! But I am installing from deb, not Flatpack and I'm not running Wayland.

**Comment by absidue** [comment]
> No – it does not only happen when the window goes out of focus. It also does while watching with that window active.

Please carefully re-read the entire sentence, I didn't say that it only happened for out of focus windows, notice the `or` which points out two conditions...

**Comment by philpagel** [comment]
I was thinking about possible external factors all day. My main question regarding this idea is: what would it take to cause the video to stop? 

- Would Freetube stop playing after receiving a signal like STOP or TERM or similar? But without terminating the program.
- Or is there an API that an external piece of software could use to tell freetube to stop playing? 
- Or does freetube monitor any acpi status parameters or anything like this?

I'm  a bit out of ideas what to look for.

**Comment by absidue** [comment]
@philpagel Could you please try a normal/traditional window manager and see if the same problem happens?

**Comment by b2ag** [comment]
> what would it take to cause the video to stop?

`systemctl --user restart pipewire` results in paused video for me.

I used FreeTube with Wayland nativ (`--ozone-platform=wayland`) in kwin_wayland and Pipewire through pipewire-pulse last time it stopped for me. I often stream audio with Snapcast Discover module for PipeWire. Also tested with reduced complexity without Pulse/PipeWire using plain old ALSA directly some time ago but it still stopped randomly. I've also seen it on a Intel GPU tablet (NixOS unstable, Wayland, KDE, PipeWire). Last time I checked for the bug was today with current head (b27f0e5) in development branch and I could reproduce it. Still talking about stopped, not paused video and still on KDE on NixOS unstable with NVIDIA graphics.

**Comment by philpagel** [comment]
I'd like to try it out with e.g. xfce but the stops are less frequent at the moment so it's hard to test. Will try on the weekend.

**Comment by philpagel** [comment]
I tried under xfce and it still stops by itself. :-(

**Comment by philpagel** [comment]
Yesterday, I upgraded to v0.23.1 Beta and it seems the problem has gone away. :-)
I'll keep testing to be sure. 

How about the others?

**Comment by b2ag** [comment]
It still stops for me with v0.23.1 Beta. But I put some more effort into debugging though and catched the event in the debugger.

Looks like the `navigator.mediaSession` fires a stop event which results in unloading the player.
https://github.com/shaka-project/shaka-player/blob/5f2b9799a4e2f006dc4222bb8199303d330acf15/ui/controls.js#L1351

Now I know how to trigger the bug at will. I simply press stop on the video in KDE Connect (other MPRIS control tools should work too) and it ends up in the same broken state. When I clear the action handler for stop the video pauses instead of stopping. So something is still reacting to a (real) stop event.

I just found out about this and need to try some more things to find a workaround and maybe understand why the handler is firing in the first place.

**Comment by philpagel** [comment]
> Yesterday, I upgraded to v0.23.1 Beta and it seems the problem has gone away. :-) I'll keep testing to be sure.

After quite a lot more testing, the problem really has gone away for me in 0.23.a beta.

**Comment by philpagel** [comment]
How should we proceed with the issue now. To me it seems that the problem that b2ag has is a different problem, as the video paused for me while it b2ag observes what seems to be player crashes. 

Should I leave this open for the other problem to keep this as its home? Should I close the issue and b2ag opens a separate one? What is best practice?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I am going to close as the original issue has been solved but i do want to help @b2ag here. To keep it all in one place if others are running into the same issue because of spontaneous playback stops

**Comment by b2ag** [comment]
I still don't know why this is happening, but when I do a `navigator.mediaSession.setActionHandler("stop", ()=>{console.error("stop")})` after the shaka-player is loaded, I get a "stop" printed to the console with a paused video randomly. So the random event indeed shows the same behavior as a stop command via MPRIS. It's way less annoying with this hack because I can just resume playback and don't lose the playhead position. But from what I can see playback has no problem with resuming instantly. Maybe I try a "player->play()" in the action handler next or try to find the other code path which pauses the player.

Also I'm unsure if I should open a bug regarding this stop behavior. Because unloading the player is not a good way to handle a stop command from a media control thingy if you ask me. I guess having the player pause instead is a more reasonable thing to expect. Currently I cannot resume a video with a play command after a stop command (without messing with the action handler) because the player is in an unloaded state after the stop.

**Comment by absidue** [comment]
This definitely sounds like something external to FreeTube in your setup is sending the stop command to FreeTube as nothing internally would cause that and you are the only user experiencing it.

As for opening a bug report for that, we use shaka-player's handling for the media control events, so bloating the app by adding our own handling just because a single user has something on their system, external to FreeTube, that is sending unnecessary stop events, is not worth it. So please don't open an issue for it. Any other user that may accidentally trigger it with a key on their keyboard would do it once, realise the mistake and never do it again.

**Comment by b2ag** [comment]
Please read my comment from last week. If my setup would send random stop event than v0.21.3 would behave similar. I justed tested v0.23.1 with a stop command from KDE Connect. It pauses the video. It never ever experienced randomly paused videos with v0.21.3. I use it all the time. So yes, also in the last weeks. With the same setup. Also there is at least one other user describing the same behavior as I see in this thread.

**Comment by b2ag** [comment]
Also try to trigger a mediaSession stop action and see if you are happy with the results. Compare the behavior to pre-shaka.

**Comment by absidue** [comment]
As there is nothing in FreeTube's code that would be causing those random stops and you are the only user experiencing it, the only options are that either something outside of FreeTube unique to your setup is causing it or something unique to your setup is triggering some very obscure bug in Electron or Chromium, either way there is no point continuing a discussion about it as there is nothing we can do about it from our side.

**Comment by absidue** [comment]
If maintaining a custom build for yourself with a workaround rather than fixing whatever is actually causing the problem in your setup is what you want to do, go for it. At the very least it will stop the notification spam from this thread.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@b2ag thank you for your continuous efforts in trying to squash this weird bug!

**Comment by b2ag** [comment]
Happy to report the issue is really gone for good for me. The weirdness of this bug almost drove me nuts. Sorry for letting my anger slip into some of my comments. ❤️
