### ISSUE TITLE
Playback Stops after Starting

### ISSUE THREAD

**Issue by MetalNeo** [FreeTubeApp/FreeTube#778]
**Behavior of the program**
Playback will occasionally buffer/stop after a video starts playing and then continue to buffer/stop forever. No errors appear. The player controls are still interactable, but nothing that I do seems to cause the video to resume. The workaround that I use is to hit the previous and next buttons in the top left to reload the video.

**Expected behavior**
I expect the video to resume after some time has passed.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Open a video.
2. Video starts playing.
3. Video begins buffering/stops.
4. Video stays stopped until the page is reloaded.

**Screenshots**
I am not sure how to get logs for FreeTube.

**Environment Information (please complete the following information):**
 - OS: Arch Linux
 - OS Version: Rolling
 - FreeTube version: Git (commit 1348)
 - Installation Method (If applicable): AUR package
- Backend: Local (with Invidious fallback enabled)

**Additional context**
I am not sure if this is a duplicate of #733 because I am not getting any error messages, but it may be related due to similar symptoms.

Side note: The default spelling of Installation under Environment Information when creating bug reports is incorrect.

**Comment by GilgusMaximus** [comment]
Okay I cannot replicate that with videos of all kinds of different lengths. 
However I am on Windows, so it might be something specific to the Linux platform. So someone with Arch could help better.
However you can see whether another error is printed in the developer console (Ctrl + Shift + I). This might help. Beware, that when you first open the developer console a lot of yellow warning are displayed, and you might have to scroll up for any errors. The warnings can be ignored.

One thing we can try (which solved an issue for me that no video loaded at all anymore) is the following. 
Could you please go the the FreeTube data directory (so where your settings, history and so on are stored) and then delete every file in the dashFiles directory. Then keep the directory open and start one of the videos which do not load for you. Is a new file created in the dashFiles directory? If yes, then it is some kind of other problem. If not, then I would ask you to save your history, profiles and subscriptions (best to just backup the whole FreeTube data folder) and delete everything from FreeTube (so uninstall and additionally delete the whole data folder of FreeTube).

If the files are generated properly, it could be that FreeTube has some issues streaming the video fast enough from YouTube. Which then is an issue on your side.

**Comment by MetalNeo** [comment]
I deleted the files and tested again, and the files do appear to be getting generated properly. However, I had a difficult time grabbing the logs (see #786). The errors I was getting are the same ones that are in that issue.

**Comment by GilgusMaximus** [comment]
Hi, so thanks for testing this anyways.
I looked through the errors in the provided logs and the main issue is that some urls cannot be found. 
However this is not completely fixed from the upstream modules as far as I know at the moment

**Comment by S-Shen** [comment]
Encountering the same issue on Windows 10 today using portables. Everything was working fine yesterday 

Attempted the following:

1. Delete all files under C:\Users\USERNAME\AppData\Roaming\FreeTube
2. Grab a fresh download (tried both _freetube-0.9.2-win-x64-portable.zip_ and _freetube-0.9.2-nightly-302-win-x64-portable.zip_)
3. Extract files and start Freetube. Leave all settings default without importing any subscription. Observe that files are generated under C:\Users\USERNAME\AppData\Roaming\FreeTube
4. Start a random video from Trending tab
5. Playback stops after a while, manually resume play, it stops after a while again. 

Looking through the console, the only 'error' I can see is 
`renderer.js:14 TypeError: Cannot read property 'url' of undefined
    at o.determineMaxFramerate (renderer.js:14)
    at o.mounted (renderer.js:14)
    at Me (renderer.js:14)
    at Xt (renderer.js:14)
    at Object.insert (renderer.js:14)
    at k (renderer.js:14)
    at o.__patch__ (renderer.js:14)
    at o.e._update (renderer.js:14)
    at o.i (renderer.js:14)
    at dn.get (renderer.js:14)`

**Comment by PrestonN** [comment]
@S-Shen Please look at #733.  This is fixed in the nightly builds.

@MetalNeo Could you please try a different installation of FreeTube?  This sounds like the issue that preventing us from updating Video.js which is mentioned [here](https://github.com/videojs/http-streaming/issues/704#event-3759751373).  You mentioned that you're using the AUR / Git installation which tells me that it's possible that they have an outdated version of Video.js without the fix.  The AUR / Git versions are not official builds and if these are the only builds that have this issue, then I will be closing this since that is up to the maintainer to make sure that those builds are properly working.

If you still have this error on an official builds (AppImage, Flatpak, Portable, etc.) then we can keep this open and research the issue further.

**Comment by S-Shen** [comment]
Grabbed [Build #303](https://github.com/FreeTubeApp/FreeTube/actions/runs/364699034). Still have the issue

**Comment by PrestonN** [comment]
@S-Shen Please try the latest nightly build once it has finished.  If it's still causing problems, then please create a new issue as this is different from the current issue that is being discussed.

**Comment by S-Shen** [comment]
@PrestonN Thank you, build #304 seems to be working fine again

**Comment by MetalNeo** [comment]
@PrestonN OK, so I tested with the latest nightly (308) and could not reproduce the issue. I also rebuilt the AUR package, and I could not reproduce the issue there either. Perhaps I built the package with an outdated version of Node.js which was causing the issue.

Issue seems to be resolved for now though, so I will be closing this issue.

**Comment by MetalNeo** [comment]
@PrestonN I have been able to reproduce this issue on nightly 310 of the portable version for Linux. [Video that error occurred on](https://invidious.snopyta.org/watch?v=aF86wufw0ZA). Errors appear to be the same looping errors as before.

[-1605975148577.log](https://github.com/FreeTubeApp/FreeTube/files/5577977/-1605975148577.log)
[-1605975153613.log](https://github.com/FreeTubeApp/FreeTube/files/5577978/-1605975153613.log)

**Comment by GilgusMaximus** [comment]
This is not related to the original error. Please look at your errors and check them first. Your connection is refused as I mentioned in your open issue. Additionally I would appreciate it if you stick to one issue instead of posting it on 3 different ones please.
