### ISSUE TITLE
Fetch more results - Local Api error

### ISSUE THREAD

**Issue by abulenok** [FreeTubeApp/FreeTube#939]
**Behavior of the program**
After clicking "Fetch more results" a Local API Error displays (invalid continuation array) 

**Expected behavior**
No error

**To Reproduce**
1. Search video title (better if there will be less results displayed, for example search "How to Use a Rekenrek Dawne Cocker" + select video duration short)
2. Click fetch more results
3. Repeat step 2 until there are no more videos to display.
3. When there are no more videos to display an error occurs.

**Screenshots**

![fetchMore-local api](https://user-images.githubusercontent.com/63914185/104810076-bed0f700-57f2-11eb-9cfb-7928a553b21d.png)

**Environment Information:**
 - OS: Windows
 - OS Version: Windows 10
 - FreeTube version: 0.11.1
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Additional context**
Our team (@Vovany4, @kgr0) has experienced this bug.

**Comment by PrestonN** [comment]
Hey there! I've just pushed out a fix for this into our dev branch.

The fetch more logic was fairly basic and didn't take into account the end of results among other things. I've updated this to take that into account and show a message when you've reached the end of a search. This will be included in the next release (likely tomorrow).

Thanks for the report!

**Comment by tekblupace** [comment]
Hi I'm using version v12 beta and still get this issue with the Fedora flatpak version.
Error: invalid continuation array
